### PR TITLE
Format code using black

### LINKED ISSUE #69: Move python code to black
For all the reason [mentioned here](https://black.readthedocs.io/en/stable/), can we move the python code to be formatted with black?

### PR DESCRIPTION
**Pull request by Carreau**
Closes #69

### CODE REVIEW

**Comment by echarles** [comment]
Thx @Carreau CI is failing with ksmm/handlers.py:151:13: E722 do not use bare 'except'
ksmm/handlers.py:156:13: E722 do not use bare 'except'

I think isort will also fail. Can you sort the import (isort...) in this PR?

Thx, Eric

**Comment by Carreau** [comment]
thanks I fixed isort, and flake8 issues.

**Review by echarles — APPROVED** [review]
Thx @Carreau

**Comment by Carreau** [comment]
Thanks !

**Pull request merged**
